"""
Script to read B92 simulation data and plot the correctness of Bob's key 
as a function of the initial key length. The data is generated by the b92_sim.py 
script, which simulates the B92 QKD protocol under different error regimes 
(low and high).
"""

import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.signal import savgol_filter
from qkd.constants import N, REPEATS

def plot_data(correctness, bit_lengths, incorrect_bits, final_key_length, regime):
    """
    Plot fidelity and success ratio of the B92 simulation across key lengths.

    Two y-axes are used: the left axis shows fidelity (percentage of Bob's
    key bits that match Alice's), and the right axis shows the success ratio
    (percentage of runs that produced a completely error-free key). Both are
    plotted against the initial key length on the x-axis.

    The mean and standard deviation lines are computed only over the
    convergent portion of the data (the final two-thirds), since short keys
    produce high variance that skews the statistics.

    Parameters
    ----------
    correctness : pd.Series
        Percentage of Bob's key bits matching Alice's for each simulation run.
    bit_lengths : pd.Series
        Initial key length used in each simulation run.
    incorrect_bits : pd.Series
        Number of mismatched bits between Alice's and Bob's keys per run.
    final_key_length : pd.Series
        Length of the reconciled key after B92 filtering (not plotted directly).
    regime : str
        Error regime used in the simulations ("low" or "high"), included in the plot title and output filename.

    Output
    ------
    Saves a PDF to source/results/B92_Fidelity_{N}_bits_{REPEATS}_repeats_{regime}.pdf.
    """
    # Skip the first third when computing summary statistics: short keys have
    # not yet converged and would pull the mean/std away from the long-key
    # asymptote we actually care about.
    cutoff = len(correctness) // 3
    mean_success = np.mean(correctness.iloc[cutoff:])
    dev_success = np.std(correctness.iloc[cutoff:])

    desired_key_length = bit_lengths // 4

    # Split runs into seven buckets by error count so each can be given a
    # distinct colour, making it easy to see where errors concentrate.
    key_length_arr = []
    transmission_success_arr = []
    for i in range(6):
        mask = incorrect_bits == i
        key_length_arr.append(desired_key_length[mask])
        transmission_success_arr.append(correctness[mask])
    key_length_arr.append(desired_key_length[incorrect_bits > 5])
    transmission_success_arr.append(correctness[incorrect_bits > 5])

    # A run is "successful" only if Bob's key is identical to Alice's (zero
    # incorrect bits). Expressed as a percentage to match the right-hand axis.
    success_ratio = (incorrect_bits == 0).astype(float) * 100

    # Average the per-run success flags across all repeats at each key length
    # to get a smooth probability curve for the right-hand axis.
    df_temp = pd.DataFrame({'l': desired_key_length.values, 's': success_ratio.values})
    sr_grouped = df_temp.groupby('l')['s'].mean()
    success_ratio_means_x = sr_grouped.index.values
    success_ratio_means = sr_grouped.values
    smoothed_success_ratio_means = savgol_filter(
        success_ratio_means, window_length=11, polyorder=3)

    # Find the key length where the protocol first reaches ~50% chance of an
    # error-free key; used as a reference marker on the plot.
    half_point = int(np.argmin(np.abs(smoothed_success_ratio_means - 50)))

    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(9, 6))
    # Twin axis lets fidelity (left) and success ratio (right) share the same
    # x-axis without conflating their different percentage scales.
    ax2 = ax.twinx()

    colors = ['deeppink', 'firebrick', 'darkorange', 'darkgoldenrod', 'gold', 'lawngreen',
              'seagreen']
    labels = ['= 0', '= 1', '= 2', '= 3', '= 4', '= 5', '> 5']

    ax.set(title=f"B92 Fidelity Simulation - {regime.capitalize()} Error Regime")
    ax.set(xlabel="Desired Key Length, bits")
    ax2.set(ylabel="Success Ratio, %")
    ax.set(ylabel="Fidelity, %")

    ax2.plot(success_ratio_means_x, smoothed_success_ratio_means,
             linestyle="dotted", color="indigo", label="n = 0 Probability")

    ax2.axvline(success_ratio_means_x[half_point], color="navy",
                label="~50% Chance of Success", linestyle="dashdot")

    for i in range(len(key_length_arr)):
        ax.scatter(key_length_arr[i], transmission_success_arr[i], color=colors[i],
                    linestyle='None', s=0.25)

    # ax2.plot(desired_key_length, success_ratio, color="indigo",
    #        linestyle="dotted", label="Mean Success Ratio")

    # ax.scatter(desired_key_length, correctness, color="teal",
    #           marker=".", linestyle='None', label="Key Length Success")

    ax.axhline(y=mean_success, color='navy',
               linestyle='-', label="Mean Correctness (convergent): " + str(round(mean_success, 3)))
    # ax.axhline(y=mean_success+dev_success, color='indigo',
    #            linestyle='--', label="Standard Deviation (convergent): " + str(round(dev_success, 3)))
    # ax.axhline(y=mean_success-dev_success, color='indigo',
    #           linestyle='--')
    print("Mean success after 1/3 was:", mean_success)
    print("Standard Deviation after 1/3 was:", dev_success)
    print("50% Chance Length At:", success_ratio_means_x[half_point])
    ax.legend(loc="lower right")
    ax2.legend(loc="lower left")
    ax.grid(alpha=0.5)
    plt.tight_layout()
    print("Saving plot to PDF...")
    output_path = (
        Path(__file__).parent.parent.parent / 'results' /
        f'B92_Fidelity_{N}_bits_{REPEATS}_repeats_{regime}.pdf'
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        plt.savefig(output_path, dpi=600)
        print(f"Plot saved successfully to {output_path}")
    except Exception as e:
        print(f"Error saving plot: {e}")

def main():
    parser = argparse.ArgumentParser(description=
        'Plot the correctness of Bob\'s key as a function of the initial key length for B92 simulations.'
    )
    parser.add_argument(
        "--regime",
        choices=["low", "high"],
        default="low",
        help="Error regime to use for probabilities and uncertainties (default: low).",
    )
    args = parser.parse_args()

    # Load the data from the corresponding CSV file based on the selected regime.
    data_path = (
        Path(__file__).parent.parent.parent / 'data' / 'b92_data' /
        f'{N}_bits_{REPEATS}_repeats_{args.regime}.csv'
    )
    try:
        data = pd.read_csv(data_path)
    except FileNotFoundError:
        print(f"Data file not found: {data_path}")
        return

    # Extract the relevant columns for plotting.
    bit_lengths = data['Initial Key Length']
    correctness = data['Correctness']
    incorrect_bits = data['Incorrect Bits']
    final_key_length = data['Final Key Length']

    plot_data(correctness, bit_lengths, incorrect_bits, final_key_length, args.regime)

if __name__ == "__main__":
    main()