"""
Script to read B92 simulation data and plot the correctness of Bob's key 
as a function of the initial key length. The data is generated by the b92_sim.py 
script, which simulates the B92 QKD protocol under different error regimes 
(low and high).
"""

def plot_data(correctness, bit_lengths, incorrect_bits, final_key_length):
    """
    Function to plot the correctness of Bob's key as a function of the initial key length.
    """
    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(9, 6))
    ax2 = ax.twinx()

    colors = ['deeppink', 'firebrick', 'darkorange', 'darkgoldenrod', 'gold', 'lawngreen',
              'seagreen']
    labels = ['= 0', '= 1', '= 2', '= 3', '= 4', '= 5', '> 5']

    ax.set(title="B92 Fidelity Simulation 8bit to 249bit Desired Length")
    ax.set(xlabel="Desired Shared Key Length")
    ax2.set(ylabel="Success Ratio, %")
    ax.set(ylabel="Percentage Correctness (After Contraction), %")

    ax2.plot(success_ratio_means_x, success_ratio_means,
             linestyle="dotted", color="indigo", label="n = 0 Probability")

    ax2.axvline(success_ratio_means_x[half_point], color="navy",
                label="~50% Chance of Success", linestyle="dashdot")

    if (not MULTICOLOUR):
        ax.scatter(graph_keys, transmission_success, color="darkgoldenrod",
                   linestyle='None', label="Transmission Success Rate", s=0.25)

    else:
        for i in range(len(key_length_arr)):
            ax.scatter(key_length_arr[i], transmission_success_arr[i], color=colors[i],
                       linestyle='None', s=0.25)

    ax2.plt(key_lengths, success_ratio, color="indigo",
           linestyle="dotted", label="Mean Success Ratio")

    ax.scatter(key_lengths, key_success, color="teal",
              marker=".", linestyle='None', label="Key Length Success")

    ax.axhline(y=mean_success, color='navy',
               linestyle='-', label="Mean Correctness (convergent): " + str(round(mean_success, 3)))
    ax.axhline(y=mean_success+dev_success, color='indigo',
               linestyle='--', label="Standard Deviation (convergent): " + str(round(dev_success, 3)))
    ax.axhline(y=mean_success-dev_success, color='indigo',
               linestyle='--')
    print("Mean success after 1/3 was:", mean_success)
    print("Standard Deviation after 1/3 was:", dev_success)
    print("50% Chance Length At:", success_ratio_means_x[half_point])
    ax.legend()
    ax2.legend(loc="lower left")
    ax.grid(alpha=0.5)
    plt.tight_layout()
    output_path = (
        Path(__file__).parent.parent / 'results' /
        f'B92_Fidelity_{N}_bits_{REPEATS}_repeats.pdf'
    )
    plt.savefig(output_path, dpi=1000)

def main():
    parser = argparse.ArgumentParser(description=
        'Plot the correctness of Bob\'s key as a function of the initial key length for B92 simulations.'
    )
    parser.add_argument(
        "--regime",
        choices=["low", "high"],
        default="low",
        help="Error regime to use for probabilities and uncertainties (default: low).",
    )
    args = parser.parse_args()

    # Load the data from the corresponding CSV file based on the selected regime.
    data_path = (
        Path(__file__).parent.parent / 'data' / 'b92_data' /
        f'{N}_bits_{REPEATS}_repeats.csv'
    )
    data = pd.read_csv(data_path)

    # Extract the relevant columns for plotting.
    bit_lengths = data['Initial Key Length']
    correctness = data['Correctness']
    incorrect_bits = data['Incorrect Bits']
    final_key_length = data['Final Key Length']

    