"""
Script to read QKD simulation data and plot the correctness of Bob's key
as a function of the initial key length. The data is generated by either
b92_sim.py or bb84_sim.py, which simulate the B92 or BB84 protocol under
different error regimes (low and high). The protocol to plot is selected
via the --protocol CLI flag.
"""

import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.signal import savgol_filter
from qkd.constants import N, RUNS



def plot_data(correctness, bit_lengths, incorrect_bits, final_key_length, regime, protocol):
    """
    Plot fidelity and success ratio of the {protocol} simulation across key lengths.

    Two y-axes are used: the left axis shows fidelity (percentage of Bob's
    key bits that match Alice's), and the right axis shows the success ratio
    (percentage of runs that produced a completely error-free key). Both are
    plotted against the initial key length on the x-axis.

    The mean and standard deviation lines are computed only over the
    convergent portion of the data (the final three-quarters), since short keys
    produce high variance that skews the statistics.

    Parameters
    ----------
    correctness : pd.Series
        Percentage of Bob's key bits matching Alice's for each simulation run.
    bit_lengths : pd.Series
        Initial key length used in each simulation run.
    incorrect_bits : pd.Series
        Number of mismatched bits between Alice's and Bob's keys per run.
    final_key_length : pd.Series
        Length of the reconciled key after filtering (not plotted directly).
    regime : str
        Error regime used in the simulations ("low" or "high"), included in the plot title and output filename.
    protocol : str
        The QKD protocol being simulated (e.g., "bb84", "b92").

    Output
    ------
    Saves a PDF to source/results/{protocol}_Fidelity_{N}_bits_{RUNS}_runs_{regime}.pdf.
    """
    # Skip the first quarter when computing summary statistics: short keys have
    # not yet converged and would pull the mean/std away from the long-key
    # asymptote we actually care about.
    cutoff = len(correctness) // 4
    mean_success = np.mean(correctness.iloc[cutoff:])
    dev_success = np.std(correctness.iloc[cutoff:])

    desired_key_length = bit_lengths // 4 if protocol == "b92" else bit_lengths // 2

    # Split runs into seven buckets by error count so each can be given a
    # distinct colour, making it easy to see where errors concentrate.
    key_length_arr = []
    transmission_success_arr = []
    for i in range(6):
        mask = incorrect_bits == i
        key_length_arr.append(desired_key_length[mask])
        transmission_success_arr.append(correctness[mask])
    key_length_arr.append(desired_key_length[incorrect_bits > 5])
    transmission_success_arr.append(correctness[incorrect_bits > 5])

    # A run is "successful" only if Bob's key is identical to Alice's (zero
    # incorrect bits). Expressed as a percentage to match the right-hand axis.
    success_ratio = (incorrect_bits == 0).astype(float) * 100

    # Average the per-run success flags across all repeats at each key length
    # to get a smooth probability curve for the right-hand axis.
    df_temp = pd.DataFrame({'l': desired_key_length.values, 's': success_ratio.values})
    sr_grouped = df_temp.groupby('l')['s'].mean()
    success_ratio_means_x = sr_grouped.index.values
    success_ratio_means = sr_grouped.values
    smoothed_success_ratio_means = savgol_filter(
        success_ratio_means, window_length=11, polyorder=3)

    # Find the key length where the protocol first reaches ~50% chance of an
    # error-free key; used as a reference marker on the plot.
    half_point = int(np.argmin(np.abs(smoothed_success_ratio_means - 50)))

    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(9, 6))
    # Twin axis lets fidelity (left) and success ratio (right) share the same
    # x-axis without conflating their different percentage scales.
    ax2 = ax.twinx()

    colors = ['deeppink', 'firebrick', 'darkorange', 'darkgoldenrod', 'gold', 'lawngreen',
              'seagreen']
    labels = ['= 0', '= 1', '= 2', '= 3', '= 4', '= 5', '> 5']

    ax.set(title=f"{protocol.upper()} Fidelity Simulation - {regime.capitalize()} Error Regime")
    ax.set(xlabel="Desired Key Length, bits")
    ax2.set(ylabel="Success Ratio (SR), %")
    ax.set(ylabel="Fidelity, %")

    ax2.plot(success_ratio_means_x, smoothed_success_ratio_means,
             linestyle="dotted", color="purple", label=f"Mean SR (smoothed)")

    for i in range(len(key_length_arr)):
        ax.scatter(key_length_arr[i], transmission_success_arr[i], color=colors[i],
                    linestyle='None', s=0.5, alpha=0.8, edgecolors='none',
                    label=f"{labels[i]} Incorrect Bits")

    ax.axhline(y=mean_success, color="navy", linestyle='-', label=f'Mean Fidelity (converged)')

    ax2.axvline(success_ratio_means_x[half_point], color="indigo",
                linestyle="dashed", label="Half-metric", alpha=0.8)
    ax2.axhline(y=50, color="indigo", linestyle="dashed", alpha=0.8)

    ax2.yaxis.set_major_locator(plt.MultipleLocator(10))

    print("Mean fidelity after 1/4 was:", mean_success)
    print("Standard Deviation after 1/4 was:", dev_success)
    print("Half-metric:", success_ratio_means_x[half_point])

    # Label the mean fidelity line directly on the left y-axis.
    ax.annotate(
        f'{round(mean_success, 3)}',
        xy=(0, mean_success),
        xycoords=('axes fraction', 'data'),
        xytext=(-6, 0),
        textcoords='offset points',
        ha='right', va='center',
        color="navy", fontsize=8,
    )

    # Label the 50%-success vertical line directly on the x-axis.
    ax.annotate(
        f'{int(round(success_ratio_means_x[half_point], 0))}',
        xy=(success_ratio_means_x[half_point], 0),
        xycoords=('data', 'axes fraction'),
        xytext=(0, -6),
        textcoords='offset points',
        ha='center', va='top',
        color="indigo", fontsize=8,
    )

    # Merge handles from both axes into a single legend placed outside the plot
    # to the upper right of the right-hand y-axis so it doesn't overlap the data.
    handles1, labels1 = ax.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax2.legend(handles1 + handles2, labels1 + labels2,
               loc='upper left', bbox_to_anchor=(1.07, 1), borderaxespad=0,
               fontsize=8, markerscale=6, handlelength=1.2)

    ax.grid(alpha=0.5)
    plt.tight_layout()
    print("Saving plot to PDF...")
    output_path = (
        Path(__file__).parent.parent.parent / 'results' /
        f'{protocol.upper()}_Fidelity_{N}_bits_{RUNS}_runs_{regime}.pdf'
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        plt.savefig(output_path, dpi=600, bbox_inches='tight')
        print(f"Plot saved successfully to {output_path}")
    except Exception as e:
        print(f"Error saving plot: {e}")

def main():
    parser = argparse.ArgumentParser(
        description="Plot the correctness of Bob's key as a function of the initial key length for B92 or BB84 simulations."
    )
    parser.add_argument(
        "--regime",
        choices=["low", "high"],
        default="low",
        help="Error regime to use for probabilities and uncertainties (default: low).",
    )
    parser.add_argument(
        "--protocol",
        choices=["bb84", "b92"],
        default="bb84",
        help="QKD protocol to plot (default: bb84).",
    )
    parser.add_argument(
        "--norm",
        action="store_true",
        help="Renormalise probabilities to ensure valid distributions (default: False)."
    )
    args = parser.parse_args()

    regime = args.regime
    if args.norm:
        regime += "_norm"

    # Load the data from the corresponding CSV file based on the selected regime.
    data_path = (
        Path(__file__).parent.parent.parent / 'data' / f'{args.protocol}_data' /
        f'{N}_bits_{RUNS}_runs_{regime}.csv'
    )
    try:
        data = pd.read_csv(data_path)
    except FileNotFoundError:
        print(f"Data file not found: {data_path}")
        return

    # Extract the relevant columns for plotting.
    bit_lengths = data['Initial Key Length']
    correctness = data['Correctness']
    incorrect_bits = data['Incorrect Bits']
    final_key_length = data['Final Key Length']

    plot_data(correctness, bit_lengths, incorrect_bits, final_key_length, regime, args.protocol)

if __name__ == "__main__":
    main()