"""
Script to read QKD simulation data and plot the correctness of Bob's key
as a function of the initial key length. The data is generated by either
b92_sim.py or bb84_sim.py, which simulate the B92 or BB84 protocol under
different error regimes (low and high). The protocol to plot is selected
via the --protocol CLI flag.
"""

import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.signal import savgol_filter
from scipy.ndimage import gaussian_filter1d
from qkd.constants import N, RUNS



def plot_data(correctness, bit_lengths, incorrect_bits, final_key_length, regime, protocol, norm):
    """
    Plot fidelity and success ratio of the {protocol} simulation across key lengths.

    Two y-axes are used: the left axis shows fidelity (percentage of Bob's
    key bits that match Alice's), and the right axis shows the success ratio
    (percentage of runs that produced a completely error-free key). Both are
    plotted against the initial key length on the x-axis.

    The mean and standard deviation lines are computed only over the
    convergent portion of the data (the final three-quarters), since short keys
    produce high variance that skews the statistics.

    Parameters
    ----------
    correctness : pd.Series
        Percentage of Bob's key bits matching Alice's for each simulation run.
    bit_lengths : pd.Series
        Initial key length used in each simulation run.
    incorrect_bits : pd.Series
        Number of mismatched bits between Alice's and Bob's keys per run.
    final_key_length : pd.Series
        Length of the reconciled key after filtering (not plotted directly).
    regime : str
        Error regime used in the simulations ("low" or "high"), included in the plot title and output filename.
    protocol : str
        The QKD protocol being simulated (e.g., "bb84", "b92").
    norm : bool
        Whether the probabilities were renormalised to ensure valid distributions; included in the plot title and
        output filename if True.

    Output
    ------
    Saves a PDF to source/results/{protocol}_Fidelity_{N}_bits_{RUNS}_runs_{regime}.pdf.
    """
    # Skip the first quarter when computing summary statistics: short keys have
    # not yet converged and would pull the mean/std away from the long-key
    # asymptote we actually care about.
    cutoff = len(correctness) // 4
    sample = correctness.iloc[cutoff:]
    mean_success = sample.mean()
    sem = sample.std(ddof=1) / np.sqrt(len(sample))

    desired_key_length = bit_lengths // 4 if protocol == "b92" else bit_lengths // 2

    # Split runs into seven buckets by error count so each can be given a
    # distinct colour, making it easy to see where errors concentrate.
    key_length_arr = []
    transmission_success_arr = []
    for i in range(6):
        mask = incorrect_bits == i
        key_length_arr.append(desired_key_length[mask])
        transmission_success_arr.append(correctness[mask])
    key_length_arr.append(desired_key_length[incorrect_bits > 5])
    transmission_success_arr.append(correctness[incorrect_bits > 5])

    # A run is "successful" only if Bob's key is identical to Alice's (zero
    # incorrect bits). Expressed as a percentage to match the right-hand axis.
    success_ratio = (incorrect_bits == 0).astype(float) * 100

    # Average the per-run success flags across all repeats at each key length
    # to get a smooth probability curve for the right-hand axis.
    df_temp = pd.DataFrame({'l': desired_key_length.values, 's': success_ratio.values})
    sr_grouped = df_temp.groupby('l')['s'].mean()
    success_ratio_means_x = sr_grouped.index.values
    success_ratio_means = sr_grouped.values
    # smoothed_success_ratio_means = savgol_filter(
    #     success_ratio_means, window_length=31, polyorder=2)
    smoothed_success_ratio_means = gaussian_filter1d(success_ratio_means, sigma=3)

    # Find the largest key length still at or below 50% success ratio: the
    # crossing point from below is more meaningful than argmin, which can
    # land on the low side of the crossing.
    above = np.where(smoothed_success_ratio_means >= 50)[0]
    half_point = int(above[-1])

    # Find the uncertainty of the half-metric using bootstrap resampling
    half_metric_uncertainty = bootstrap_half_metric(df_temp, success_ratio_means_x)

    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(9, 6))
    # Twin axis lets fidelity (left) and success ratio (right) share the same
    # x-axis without conflating their different percentage scales.
    ax2 = ax.twinx()

    colors = ['deeppink', 'firebrick', 'darkorange', 'darkgoldenrod', 'gold', 'lawngreen',
              'seagreen']
    labels = ['= 0', '= 1', '= 2', '= 3', '= 4', '= 5', '> 5']

    ax.set(title=f"{protocol.upper()} Fidelity Simulation - {regime.capitalize()} Error Regime {'Normalised' if norm else ''}")
    ax.set(xlabel="Desired Key Length, bits")
    ax2.set(ylabel="Success Ratio (SR), %")
    ax.set(ylabel="Fidelity, %")

    ax2.plot(success_ratio_means_x, smoothed_success_ratio_means,
             linestyle="dotted", color="purple", label=f"Mean SR (smoothed)")

    for i in range(len(key_length_arr)):
        ax.scatter(key_length_arr[i], transmission_success_arr[i], color=colors[i],
                    linestyle='None', s=0.5, alpha=0.8, edgecolors='none',
                    label=f"{labels[i]} Incorrect Bits")

    ax.axhline(y=mean_success, color="navy", linestyle='-', label=f'Mean Fidelity (converged):\n  ({mean_success:.3f} ± {sem:.3f})%')

    ax2.axvline(success_ratio_means_x[half_point], color="indigo",
                linestyle="dashed", label=f'Half-metric: ({int(round(success_ratio_means_x[half_point], 0))} ± {half_metric_uncertainty:.0f}) bits', alpha=0.8)
    ax2.axhline(y=50, color="indigo", linestyle="dashed", alpha=0.8)

    ax2.yaxis.set_major_locator(plt.MultipleLocator(10))

    print(f"Mean fidelity after 1/4 was: {mean_success:.4f}")
    print(f"SEM after 1/4 was: {sem:.4f}")
    print(f"Half-metric: {success_ratio_means_x[half_point]}")
    print(f"Half-metric uncertainty: {half_metric_uncertainty:.0f}")

    # Merge handles from both axes into a single legend placed outside the plot
    # to the upper right of the right-hand y-axis so it doesn't overlap the data.
    handles1, labels1 = ax.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax2.legend(handles1 + handles2, labels1 + labels2,
               loc='upper left', bbox_to_anchor=(1.07, 1), borderaxespad=0,
               fontsize=8, markerscale=6, handlelength=1.2)

    ax.grid(alpha=0.5)
    plt.tight_layout()
    print("Saving plot to PDF...")
    output_path = (
        Path(__file__).parent.parent.parent / 'results' /
        f'{protocol.upper()}_Fidelity_{N}_bits_{RUNS}_runs_{regime}{"" if not norm else "_norm"}.pdf'
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        plt.savefig(output_path, dpi=600, bbox_inches='tight')
        print(f"Plot saved successfully to {output_path}")
    except Exception as e:
        print(f"Error saving plot: {e}")

def bootstrap_half_metric(df_temp, success_ratio_means_x, num_bootstrap=1000, window_length=11, polyorder=2):
    """
    Perform bootstrap resampling to estimate the uncertainty of the half-metric.
    """
    rng = np.random.default_rng(seed=42)
    half_metrics = []
    for _ in range(num_bootstrap):
        sample_df = df_temp.sample(frac=1, replace=True)
        sr_grouped = sample_df.groupby('l')['s'].mean()
        sr_aligned = sr_grouped.reindex(success_ratio_means_x, fill_value=np.nan)
        if sr_aligned.isna().any():
            continue
        # smoothed_sr = savgol_filter(sr_aligned.values, window_length=window_length, polyorder=polyorder)
        smoothed_sr = gaussian_filter1d(sr_aligned.values, sigma=3)
        above = np.where(smoothed_sr >= 50)[0]
        index = int(above[-1])
        half_metrics.append(success_ratio_means_x[index])

    return np.std(half_metrics, ddof=1)


def main():
    parser = argparse.ArgumentParser(
        description="Plot the correctness of Bob's key as a function of the initial key length for B92 or BB84 simulations."
    )
    parser.add_argument(
        "--regime",
        choices=["low", "high"],
        default="low",
        help="Error regime to use for probabilities and uncertainties (default: low).",
    )
    parser.add_argument(
        "--protocol",
        choices=["bb84", "b92"],
        default="bb84",
        help="QKD protocol to plot (default: bb84).",
    )
    parser.add_argument(
        "--norm",
        action="store_true",
        help="Renormalise probabilities to ensure valid distributions (default: False)."
    )
    args = parser.parse_args()

    regime = args.regime
    if args.norm:
        regime += "_norm"

    # Load the data from the corresponding CSV file based on the selected regime.
    data_path = (
        Path(__file__).parent.parent.parent / 'data' / f'{args.protocol}_data' /
        f'{N}_bits_{RUNS}_runs_{regime}.csv'
    )
    try:
        data = pd.read_csv(data_path)
    except FileNotFoundError:
        print(f"Data file not found: {data_path}")
        return

    # Extract the relevant columns for plotting.
    bit_lengths = data['Initial Key Length']
    correctness = data['Correctness']
    incorrect_bits = data['Incorrect Bits']
    final_key_length = data['Final Key Length']

    plot_data(correctness, bit_lengths, incorrect_bits, final_key_length, args.regime, args.protocol, args.norm)

if __name__ == "__main__":
    main()